api:
  dashboard: true
  debug: true

entryPoints:
  http:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: https
          scheme: https

  https:
    address: ":443"

serversTransport:
  insecureSkipVerify: false

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
  file:
    filename: /config.yml
    directory: /custom
    watch: true

certificatesResolvers:
  letsencrypt:
    acme:
      email: hrust.nsk@gmail.com
      storage: /acme.json
      httpChallenge:
        entryPoint: http
