upstreams:
  strategy: parallel_best
  groups:
    default:
    - https://dns.cloudflare.com/dns-query
    - https://dns10.quad9.net/dns-query
    - https://dns.adguard-dns.com/dns-query
    - https://zero.dns0.eu/
    - https://dns.controld.com/comss

blocking:
  denylists:
    ads:
      - https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
      - https://cdn.jsdelivr.net/gh/hagezi/dns-blocklists@latest/wildcard/ultimate.txt
      - https://cdn.jsdelivr.net/gh/hagezi/dns-blocklists@latest/wildcard/popupads.txt
      - https://cdn.jsdelivr.net/gh/hagezi/dns-blocklists@latest/wildcard/fake.txt
      - https://cdn.jsdelivr.net/gh/hagezi/dns-blocklists@latest/wildcard/tif.txt
    suspicious:
      - https://raw.githubusercontent.com/PolishFiltersTeam/KADhosts/master/KADhosts.txt
      - https://raw.githubusercontent.com/FadeMind/hosts.extras/master/add.Spam/hosts
      - https://v.firebog.net/hosts/static/w3kbl.txt
    advertising:
      - https://adaway.org/hosts.txt
      - https://v.firebog.net/hosts/AdguardDNS.txt
      - https://v.firebog.net/hosts/Admiral.txt
      - https://raw.githubusercontent.com/anudeepND/blacklist/master/adservers.txt
      - https://v.firebog.net/hosts/Easylist.txt
      - https://pgl.yoyo.org/adservers/serverlist.php?hostformat=hosts&showintro=0&mimetype=plaintext
      - https://raw.githubusercontent.com/FadeMind/hosts.extras/master/UncheckyAds/hosts
      - https://raw.githubusercontent.com/bigdargon/hostsVN/master/hosts
    tracking-telemetry:
      - https://v.firebog.net/hosts/Easyprivacy.txt
      - https://v.firebog.net/hosts/Prigent-Ads.txt
      - https://raw.githubusercontent.com/FadeMind/hosts.extras/master/add.2o7Net/hosts
      - https://raw.githubusercontent.com/crazy-max/WindowsSpyBlocker/master/data/hosts/spy.txt
      - https://hostfiles.frogeye.fr/firstparty-trackers-hosts.txt
    malicious:
      - https://raw.githubusercontent.com/DandelionSprout/adfilt/master/Alternate%20versions%20Anti-Malware%20List/AntiMalwareHosts.txt
      - https://osint.digitalside.it/Threat-Intel/lists/latestdomains.txt
      - https://v.firebog.net/hosts/Prigent-Crypto.txt
      - https://raw.githubusercontent.com/FadeMind/hosts.extras/master/add.Risk/hosts
      - https://bitbucket.org/ethanr/dns-blacklists/raw/8575c9f96e5b4a1308f2f12394abd86d0927a4a0/bad_lists/Mandiant_APT1_Report_Appendix_D.txt
      - https://phishing.army/download/phishing_army_blocklist_extended.txt
      - https://gitlab.com/quidsup/notrack-blocklists/raw/master/notrack-malware.txt
      - https://v.firebog.net/hosts/RPiList-Malware.txt
      - https://v.firebog.net/hosts/RPiList-Phishing.txt
      - https://raw.githubusercontent.com/Spam404/lists/master/main-blacklist.txt
      - https://raw.githubusercontent.com/AssoEchap/stalkerware-indicators/master/generated/hosts
      - https://urlhaus.abuse.ch/downloads/hostfile/
    other:
      - https://zerodot1.gitlab.io/CoinBlockerLists/hosts_browser
  clientGroupsBlock:
    default:
      - ads
      - suspicious
      - advertising
      - trackers-hosts
      - malicious
      - other
  blockType: zeroIp

customDNS:
  customTTL: 1h
  filterUnmappedTypes: true
  mapping:
      qnap.a87p.ru: 192.168.1.30
      traefik.a87p.ru: 192.168.1.30
      vnc.a87p.ru: 192.168.1.30
      kuma.a87p.ru: 192.168.1.30
      gotify.a87p.ru: 192.168.1.30
      igotify.a87p.ru: 192.168.1.30

bootstrapDns:
      - upstream: tcp-tls:dns.quad9.net
        ips:
        - 9.9.9.9
        - 149.112.112.112
      - upstream: https://1.1.1.1/dns-query

clientLookup:
  upstream: 192.168.1.1
  clients:
    proxmox-vds:
      - 192.168.1.119
    ubuntu-docker:
      - 192.168.1.30
    yoitepc:
      - 192.168.1.56
    hrustpc:
      - 192.168.1.55
    yoiteiphone:
      - 192.168.1.77
    hrustiphone:
      - 192.168.1.76
    ipad11pro:
      - 192.168.1.75
    qnap:
      - 192.168.1.5
    nvidiashieldtv:
      - 192.168.1.85
    sonyht-st9:
      - 192.168.1.149
    canonmfy:
      - 192.168.1.193
    xiaomitv:
      - 192.168.1.86
    yoitenotebook:
      - 192.168.1.163
    roomba:
      - 192.168.1.142
    philips55:
      - 192.168.1.144
    xiaomiris:
      - 192.168.1.160

caching:
  minTime: 5m
  maxTime: 30m
  prefetching: true
  prefetchExpires: 2h
  prefetchThreshold: 5

prometheus:
  enable: true

ports:
  dns: 53
  http: 4000
