services:
  mysql:
    image: mysql:8.4
    container_name: guacmysql
    environment:
      MYSQL_DATABASE: guacamole
      MYSQL_USER: guacuser
      MYSQL_PASSWORD: guacPA55
      MYSQL_ROOT_PASSWORD: myROOTpa55
    volumes:
      - ./mysql:/var/lib/mysql
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      proxy:

  guacd:
    image: guacamole/guacd
    container_name: guacd
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    depends_on:
      - mysql
    networks:
      proxy:

  guacamole:
    image: guacamole/guacamole
    container_name: guacamole
    environment:
      MYSQL_HOSTNAME: mysql
      MYSQL_DATABASE: guacamole
      MYSQL_USER: guacuser
      MYSQL_PASSWORD: guacPA55
      GUACD_HOSTNAME: guacd
#    ports:
#      - '8080:8080'
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    depends_on:
      - mysql
      - guacd
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.guacamole.entrypoints=http"
      - "traefik.http.routers.guacamole.rule=Host(`vnc.domen                .ru`)"
      - "traefik.http.middlewares.guacamole-auth.basicauth.users=Name:password"
      - "traefik.http.middlewares.guacamole-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.guacamole.middlewares=guacamole-https-redirect"
      - "traefik.http.routers.guacamole-secure.entrypoints=https"
      - "traefik.http.routers.guacamole-secure.rule=Host(`vnc.domen.ru`)"
      - "traefik.http.routers.guacamole-secure.middlewares=guacamole-auth"
      - "traefik.http.routers.guacamole-secure.tls=true"
      - "traefik.http.routers.guacamole-secure.service=guacamole"
      - "traefik.http.services.guacamole.loadbalancer.server.port=8080"
      - "traefik.docker.network=proxy"
    networks:
      proxy:

networks:
  proxy:
    external: true

